apiVersion: v1
kind: Namespace
metadata:
  name: demo-knative
---
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: broker-ingress
  namespace: demo-knative
---
apiVersion: sources.knative.dev/v1alpha1
kind: SinkBinding
metadata:
  name: bind-forwarder
  namespace: demo-knative
spec:
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Configuration
    name: color-changer
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: broker-ingress
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: event-display
  namespace: demo-knative
spec:
  template:
    spec:
      containers:
        - image: gcr.io/knative-releases/knative.dev/eventing-contrib/cmd/event_display
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: event-display
  namespace: demo-knative
spec:
  broker: broker-ingress
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display
