apiVersion: serving.knative.dev/v1
kind: Configuration
metadata:
  name: color-changer
  namespace: demo-knative
spec:
  template:
    spec:
      containers:
        - image: ko://github.com/pierdipi/demo-knative/demo/source/cmd/color-changer
          env:
            - name: COLOR
              value: "green"