apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: event-display
  namespace: demo
spec:
  template:
    spec:
      containers:
        - image: gcr.io/knative-releases/knative.dev/eventing-contrib/cmd/event_display
---
apiVersion: eventing.knative.dev/v1beta1
kind: Trigger
metadata:
  name: after-taxes
  namespace: demo
spec:
  broker: products
  filter:
    attributes:
      type: "com.supermarket.products.created.taxed"
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display
      namespace: demo
