apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
networking:
  serviceSubnet: "10.96.0.0/12"
  podSubnet: "10.244.0.0/16"
nodes:
- role: control-plane
  image: kindest/node:v1.20.2@sha256:8f7ea6e7642c0da54f04a7ee10431549c0257315b3a634f6ef2fecaaedb19bab
  extraPortMappings:
  - containerPort: 32000
    hostPort: 80
