apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: istio-system
  labels:
    app: istio-ingressgateway
    install.operator.istio.io/owning-resource: unknown
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio: ingressgateway
    istio.io/rev: default
    operator.istio.io/component: IngressGateways
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.8.3
    release: istio
spec:
  clusterIP: 10.111.35.217
  clusterIPs: 
  - 10.111.35.217
  externalTrafficPolicy: Cluster
  ports:
  - name: status-port
    nodePort: 32449
    port: 15021
    protocol: TCP
    targetPort: 15021
  - name: http2
    nodePort: 32000
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    nodePort: 32010
    port: 443
    protocol: TCP
    targetPort: 8443
  - name: tcp-istiod
    nodePort: 30770
    port: 15012
    protocol: TCP
    targetPort: 15012
  - name: tls
    nodePort: 30762
    port: 15443
    protocol: TCP
    targetPort: 15443
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  sessionAffinity: None
  type: NodePort
