apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-server-source-events-sa
  namespace: demo-knative
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: api-server-source-events-sa
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: api-server-source-events-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: api-server-source-events-sa
subjects:
  - kind: ServiceAccount
    name: api-server-source-events-sa
    namespace: demo-knative
---
apiVersion: sources.knative.dev/v1
kind: ApiServerSource
metadata:
  name: api-events
  namespace: demo-knative
spec:
  serviceAccountName: api-server-source-events-sa
  mode: Resource
  resources:
    - apiVersion: v1
      kind: Event
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: broker
      namespace: demo-knative